### ISSUE TITLE
[v2.2.12]I/O error when accessing bitbucket server with protocol 'https'

### ISSUE THREAD

**Issue by elainewu03** [jenkinsci/bitbucket-branch-source-plugin#181]
We're using bitbucket-branch-source-plugin to support PR build and our bitbucket server website is secured. Therefore we have to use https to access bitbucket server. But this plugin seems it doesn't support https and return below error. Is there any user who is using https to access bitbucket server? If yes, could you please share the working solution, thanks in advance!
```
Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at 
```

**Comment by casz** [comment]
add your root certificate to the java keystore.

**Comment by casz** [comment]
Honestly, have nothing to do with the plugin.  
Fundamental java runtime management issue.
