### ISSUE TITLE
NPE when PRs scanned

### ISSUE THREAD

**Issue by tst-nstires** [jenkinsci/bitbucket-branch-source-plugin#205]
- [x] Jenkins version
2.181
- [x] Plugin version
2.4.4
- [x] Bitbucket cloud
Yes
- [ ] Bitbucket server and version
N/A

Not sure when this started, but we're unable to scan PRs & Tags. This is something that had worked previously. Only changes were updating Jenkins server, and potentially updated plugins.

BitBucket Cloud

```
# rpm -qa | grep jenkins
jenkins-2.181-1.1.noarch
```
```
# cat /etc/*release
NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"
Amazon Linux release 2 (Karoo)
```

```
# rpm -qa | grep git
lm_sensors-libs-3.4.0-4.20160601gitf9185e5.amzn2.0.2.x86_64
python-pillow-2.0.0-19.gitd1c6db8.amzn2.0.2.x86_64
crontabs-1.11-6.20121102git.amzn2.noarch
screen-4.1.0-0.25.20120314git3c2946.amzn2.x86_64
net-tools-2.0-0.22.20131004git.amzn2.0.2.x86_64
python2-future-0.16.0-15.20181019gitbee0f3b.el7.noarch
git-core-doc-2.17.2-2.amzn2.noarch
git-2.17.2-2.amzn2.x86_64
git-core-2.17.2-2.amzn2.x86_64
git-lfs-2.4.2-2.el7.x86_64
```

Plugins:
```
Amazon EC2 plugin 1.43	
Amazon Web Services SDK 1.11.562	
Ansible plugin 1.0		
Ant Plugin 1.9		
Apache HttpComponents Client 4.x API Plugin 4.5.5-3.0		
Authentication Tokens API Plugin 1.3		
Autofavorite for Blue Ocean 1.2.4	
Bitbucket Branch Source Plugin 2.4.4	
Bitbucket Pipeline for Blue Ocean 1.17.0	
Bitbucket Plugin 1.1.9	
Blue Ocean 1.17.0	
Blue Ocean Core JS 1.17.0	
Blue Ocean Executor Info 1.17.0	
Blue Ocean Pipeline Editor 1.17.0	
bouncycastle API Plugin 2.17		
Branch API Plugin 2.5.2	
Build Timeout 1.19		
build-metrics 1.3		
CloudBees AWS Credentials Plugin 1.27	
Command Agent Launcher Plugin 1.3		
Common API for Blue Ocean 1.17.0	
Config API for Blue Ocean 1.17.0	
Config File Provider Plugin 3.6.2	
Credentials Binding Plugin 1.19	
Credentials Plugin 2.2.0	
Dashboard for Blue Ocean 1.17.0	
Design Language 1.17.0	
Disable GitHub Multibranch Status Plugin 1.1		
Display URL API 2.3.1	
Display URL for Blue Ocean 2.3.0	
Docker Commons Plugin 1.15	
Docker Pipeline 1.18	
Durable Task Plugin 1.29		
Email Extension Plugin 2.66	
Events API for Blue Ocean 1.17.0	
External Monitor Job Type Plugin 1.7		
Favorite 2.3.2		
Folders Plugin 6.9	
Git client plugin 2.8.0	
Git Pipeline for Blue Ocean 1.17.0	
Git plugin 3.10.0	
Git PreBuildMerge Trait Plugin 1.0		
GIT server Plugin 1.7		
GitHub API Plugin 1.95		
GitHub Branch Source Plugin 2.5.3	
GitHub Pipeline for Blue Ocean 1.17.0	
GitHub plugin 1.29.4		
Google Login Plugin 1.4		
Gradle Plugin 1.32	
Green Balls 1.15		
Handy Uri Templates 2.x API Plugin 2.1.7-1.0		
HTML Publisher plugin 1.18		
Hudson global-build-stats plugin 1.5		
i18n for Blue Ocean 1.17.0	
Jackson 2 API Plugin 2.9.9	
Javadoc Plugin 1.5		
JavaScript GUI Lib: ACE Editor bundle plugin 1.1		
JavaScript GUI Lib: Handlebars bundle plugin 1.1.1		
JavaScript GUI Lib: jQuery bundles (jQuery and jQuery UI) plugin 1.2.1		
JavaScript GUI Lib: Moment.js bundle plugin 1.1.1		
JDK Tool Plugin 1.2		
JIRA Integration for Blue Ocean 1.17.0	
JIRA plugin This plugin integrates Jenkins to Atlassian JIRA. 3.0.7	
JSch dependency plugin  0.1.55		
JUnit Plugin 1.28	
JWT for Blue Ocean 1.17.0	
LDAP Plugin  1.20		
Lockable Resources plugin 2.5	
Mailer Plugin 1.23		
Matrix Authorization Strategy Plugin 2.4.2	
Matrix Project Plugin 1.14		
Mercurial plugin 2.6	
Nexus Artifact Uploader 2.10		
Node Iterator API Plugin 1.5.0		
OWASP Markup Formatter Plugin 1.5		
PAM Authentication plugin 1.5.1	
Personalization for Blue Ocean 1.17.0	
Pipeline 2.6		
Pipeline Graph Analysis Plugin 1.10	
Pipeline implementation for Blue Ocean 1.17.0	
Pipeline SCM API for Blue Ocean 1.17.0	
Pipeline Utility Steps 2.3.0		
Pipeline: API 2.35	
Pipeline: Basic Steps 2.18	
Pipeline: Build Step 2.9	
Pipeline: Declarative 1.3.9	
Pipeline: Declarative Agent API 1.1.1		
Pipeline: Declarative Extension Points API 1.3.9	
Pipeline: GitHub Groovy Libraries 1.0		
Pipeline: Groovy 2.70	
Pipeline: Input Step 2.10	
Pipeline: Job 2.32		
Pipeline: Milestone Step 1.3.1
Pipeline: Model API 1.3.9
Pipeline: Multibranch 2.21
Pipeline: Multibranch with defaults 2.0
Pipeline: Nodes and Processes 2.31
Pipeline: REST API Plugin 2.11
Pipeline: SCM Step 2.9
Pipeline: Shared Groovy Libraries 2.13
Pipeline: Stage Step 2.3
Pipeline: Stage Tags Metadata 1.3.9
Pipeline: Stage View Plugin 2.11
Pipeline: Step API 2.20
Pipeline: Supporting APIs 3.3
Plain Credentials Plugin 1.5
Pub-Sub "light" Bus 1.12
Purge Build Queue Plugin 1.0
Repository Connector 1.2.6
Resource Disposer Plugin 0.12
REST API for Blue Ocean 1.17.0
REST Implementation for Blue Ocean 1.17.0
SCM API Plugin 2.5.0
Script Security Plugin 1.60
Server Sent Events (SSE) Gateway Plugin 1.17
Slack Notification Plugin 2.26
SSH Agent Plugin 1.17
SSH Credentials Plugin 1.17
SSH Slaves plugin 1.30.0
Structs Plugin 1.19
This plugin exposes the DTKit 2 APIs to other Jenkins plugins. 2.1.1
Timestamper 1.9
Token Macro Plugin 2.8
Variant Plugin 1.2
Web for Blue Ocean 1.17.0
WMI Windows Agents Plugin 1.4		
Workspace Cleanup Plugin 0.37		
xUnit plugin 2.3.5
```

Error:
```
Started by timer
[Wed Jun 19 14:57:00 UTC 2019] Starting branch indexing...
Connecting to https://bitbucket.org using <redacted_username>/****** (bitbucket)
Repository type: Git
Looking up <redacted_org>/<redacted_repo> for branches
Checking branch 1234-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1235-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1236-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1237-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1238-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1239-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1240-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1241-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1242-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1243-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1244-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1245-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1246-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1247-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1248-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1249-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1250-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1251-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1252-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1253-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1254-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1255-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch 1256-Redacted-branch-name from <redacted_org>/<redacted_repo>
Checking branch dev from <redacted_org>/<redacted_repo>
ERROR: [Wed Jun 19 14:57:35 UTC 2019] Could not fetch branches from source <redacted_numbers>
java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequestValueDestination.<init>(BitbucketPullRequestValueDestination.java:53)
	at sun.reflect.GeneratedConstructorAccessor180.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
Caused: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequestValueDestination`, problem: `java.lang.NullPointerException`
 at [Source: (StringReader); line: 1, column: 14925] (through reference chain: com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequests["values"]->java.util.ArrayList[3]->com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequestValue["destination"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at com.cloudbees.jenkins.plugins.bitbucket.JsonParser.toJava(JsonParser.java:55)
	at com.cloudbees.jenkins.plugins.bitbucket.JsonParser.toJava(JsonParser.java:47)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getPullRequests(BitbucketCloudApiClient.java:291)
Caused: java.io.IOException: I/O error when parsing response from URL: https://api.bitbucket.org/2.0/repositories/<redacted_org>/<redacted_repo>/pullrequests?page=1&pagelen=50
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getPullRequests(BitbucketCloudApiClient.java:293)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource$1.create(BitbucketSCMSource.java:554)
	at com.cloudbees.jenkins.plugins.bitbucket.LazyIterable.iterator(LazyIterable.java:57)
	at com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait$ExcludeOriginPRBranchesSCMHeadFilter.isExcluded(BranchDiscoveryTrait.java:244)
	at jenkins.scm.api.trait.SCMSourceRequest.isExcluded(SCMSourceRequest.java:196)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:333)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveBranches(BitbucketSCMSource.java:748)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:589)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:634)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1025)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
[Wed Jun 19 14:57:35 UTC 2019] Finished branch indexing. Indexing took 34 sec
FATAL: Failed to recompute children of geep-all
java.io.IOException: I/O error when parsing response from URL: https://api.bitbucket.org/2.0/repositories/<redacted_org>/<redacted_repo>/pullrequests?page=1&pagelen=50
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getPullRequests(BitbucketCloudApiClient.java:293)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource$1.create(BitbucketSCMSource.java:554)
	at com.cloudbees.jenkins.plugins.bitbucket.LazyIterable.iterator(LazyIterable.java:57)
	at com.cloudbees.jenkins.plugins.bitbucket.BranchDiscoveryTrait$ExcludeOriginPRBranchesSCMHeadFilter.isExcluded(BranchDiscoveryTrait.java:244)
	at jenkins.scm.api.trait.SCMSourceRequest.isExcluded(SCMSourceRequest.java:196)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:333)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveBranches(BitbucketSCMSource.java:748)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:589)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:283)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:634)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1025)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequestValueDestination`, problem: `java.lang.NullPointerException`
 at [Source: (StringReader); line: 1, column: 14925] (through reference chain: com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequests["values"]->java.util.ArrayList[3]->com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequestValue["destination"])
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1608)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:484)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:503)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:285)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator.createFromObjectWith(ValueInstantiator.java:229)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:195)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:422)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1287)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:326)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:159)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:286)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4013)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3049)
	at com.cloudbees.jenkins.plugins.bitbucket.JsonParser.toJava(JsonParser.java:55)
	at com.cloudbees.jenkins.plugins.bitbucket.JsonParser.toJava(JsonParser.java:47)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getPullRequests(BitbucketCloudApiClient.java:291)
	... 15 more
Caused by: java.lang.NullPointerException
	at com.cloudbees.jenkins.plugins.bitbucket.client.pullrequest.BitbucketPullRequestValueDestination.<init>(BitbucketPullRequestValueDestination.java:53)
	at sun.reflect.GeneratedConstructorAccessor180.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.fasterxml.jackson.databind.introspect.AnnotatedConstructor.call(AnnotatedConstructor.java:124)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromObjectWith(StdValueInstantiator.java:283)
	... 35 more
Finished: FAILURE
```

Repo config:
![BB_multibranch_settings](https://user-images.githubusercontent.com/3965285/59781897-d0ef5a00-928a-11e9-879a-6681fefa05d7.jpg)

**Comment by grEvenX** [comment]
🔥  We got the same on one of our projects. For us the reason was that we had a Pull-Request open that target a no longer existing branch. So a pull request with a destination branch that no longer existed caused this error to appear. Once we declined that PR, the job started working again.

**Comment by marc0s** [comment]
We're experiencing this issue in some PRs but they actually have an existing destination branch.

Any thing to try before trying to recreate the PR?

Thanks!

**Comment by quasarea** [comment]
@marc0s @grEvenX but whats the scope? I have checked all open pull requests on a project (20 repos) and none points to non-existing branch, could it be declined pull request that does so?

**Comment by gregsymons** [comment]
We ran into this issue here. In our case, the branch the PR was targeting was deleted before the PR was merged. I'm not sure what Bitbucket maybe _should_ have done, but what it _did_ do was null out just the `commit` field in the `destination`. We retargeted the PR and everything started working again. It looks like at least the `commit` field in the `destination` field is nullable.

**Comment by casz** [comment]
Feel free to send a PR that can handle it and at least log it.

**Comment by mashayev** [comment]
What is the status for this issue?

**Comment by casz** [comment]
Same as last: https://github.com/jenkinsci/bitbucket-branch-source-plugin/issues/205#issuecomment-523990175

**Comment by n0rig** [comment]
May be related: https://issues.jenkins-ci.org/browse/JENKINS-57775
