### ISSUE TITLE
Intermittent build failures - read timed out

### ISSUE THREAD

**Issue by timpeeters** [jenkinsci/bitbucket-branch-source-plugin#213]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Jenkins version: 2.176.2
Plugin version: 2.4.5
Bitbucket cloud

We are experiencing issues with the `bitbucket-branch-source-plugin`. From time to time, our builds fail with the following exception. This mainly seems to happen at night when running jobs via the cron trigger. What we suspect is that the http connection pool used by the `BitbucketCloudApiClient` contains stale connections when they have not been used for several minutes/hours.

```
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.executeMethod(BitbucketCloudApiClient.java:769)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequestAsInputStream(BitbucketCloudApiClient.java:792)
Caused: java.io.IOException: Communication error for url: https://api.bitbucket.org/2.0/repositories/[redacted]/[redacted]/refs/branches
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequestAsInputStream(BitbucketCloudApiClient.java:811)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequest(BitbucketCloudApiClient.java:816)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getBranchesByRef(BitbucketCloudApiClient.java:457)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getBranches(BitbucketCloudApiClient.java:449)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:812)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:582)
	at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:98)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:293)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
```

**Comment by timpeeters** [comment]
We created a PR that registers a retry handler in the Apache HttpClient. We have been testing this PR with success, using a private build of the bitbucket-branch-source-plugin.

We would love for someone to review the PR and merge it if possible. Suggestions, improvements or alternative solutions to the issue described above are also welcome. We will update the PR or create a new one if necessary.

Thanks in advance.

**Comment by alanjcastonguay** [comment]
I'm also seeing a lot of transient errors when updating build status, both at the start and end of a build, via `com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postBuildStatus`. That's _not quite idempotent_, but I don't think retries would be bad here either.

```
[Bitbucket] Notifying pull request build result
ERROR: Could not send notifications
java.io.IOException: Communication error
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.doRequest(BitbucketCloudApiClient.java:861)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postRequest(BitbucketCloudApiClient.java:902)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.postBuildStatus(BitbucketCloudApiClient.java:607)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketChangesetCommentNotifier.buildStatus(BitbucketChangesetCommentNotifier.java:50)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications.createStatus(BitbucketBuildStatusNotifications.java:143)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications.sendNotifications(BitbucketBuildStatusNotifications.java:185)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications.access$000(BitbucketBuildStatusNotifications.java:60)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketBuildStatusNotifications$JobCompletedListener.onCompleted(BitbucketBuildStatusNotifications.java:257)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:584)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$1000(WorkflowRun.java:133)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun$GraphL.onNewHead(WorkflowRun.java:996)
	at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.notifyListeners(CpsFlowExecution.java:1463)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$3.run(CpsThreadGroup.java:458)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$1.run(CpsVmExecutorService.java:37)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.executeMethod(BitbucketCloudApiClient.java:759)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.doRequest(BitbucketCloudApiClient.java:843)
	... 22 more
Finished: SUCCESS
```

**Comment by alanjcastonguay** [comment]
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/7c761939e6b950adbadb08ede737ac3b51470002/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java#L151 

The socket timeout above is currently hardcoded to 60 * 1000 milliseconds, aka 1 minute. I see failures like the above logged at ~6 minutes after the last successful "[Bitbucket] Notifying pull request build result" logged.

**Comment by alanjcastonguay** [comment]
@casz could you provide your thoughts on this issue? Are we looking in the right (or same) place?

**Comment by casz** [comment]
@alanjcastonguay if you follow the code everything `doRequest` goes to `executeMethod` and I assume what your seeing is API rate limiting.

https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/7c761939e6b950adbadb08ede737ac3b51470002/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/client/BitbucketCloudApiClient.java#L747-L774

**Comment by mhworth** [comment]
This is happening to me too. Might be bitbucket performance issues? Having a retry loop would be great here. Our builds are failing 30-40% of the time at the moment because of this. Retrying the build usually always works.

**Comment by ken210** [comment]
Hello, I'm having the same issue here. I'm talking to bitbucket support, but they told me that api rate limits should return a 429 (too many requests).

I'm interested in the retry approach. Is it working for you, @timpeeters ?

**Comment by alanjcastonguay** [comment]
I cranked up the logging level and reproduced a bunch of failures - that `LOGGER.fine()` about bitbucket API rate limiting isn't logged. Which is consistent with observations - the failure isn't immediate but appears to follow a timeout pattern.

**Comment by joshuabergeron** [comment]
Been having the same issue here for a few weeks now. It has been pretty random/intermittent for me. I am glad to see I'm not alone!

**Comment by alanjcastonguay** [comment]
Found https://issues.jenkins-ci.org/browse/JENKINS-58810 - appears to be similar to some of the above.

**Comment by alanjcastonguay** [comment]
@timpeeters Your presenting symptom doesn't match mine, though I suspect they have the same underlying cause (something with stale keepalives in the connection pool). Your proposed resolution (retries of idempotent GET requests for branch list) will not help with my presenting symptom (failure of POST request updating build status).

If there's a bunch of people experiencing each symptom, this thread will become confusing. I don't want to distract from your original concern and proposal. Do you think there should be two separate GitHub issues (eventually with one possibly closed as duplicate of the other)? Or mutate the title/description of this one to the more general case?

**Comment by joshuabergeron** [comment]
Hmm, I am curious what indicated stale keepalives in the connection pool? Would tuning linux kernel values for net.ipv4.tcp_keepalive_time help with that?

**Comment by alanjcastonguay** [comment]
@joshuabergeron _Gut feeling about timing_ indicated stale keepalives in the connection pool, I have no hard evidence to back that up (yet). Sorry.

**Comment by joshuabergeron** [comment]
@alanjcastonguay Ah gotcha. Well I will happily reduce net.ipv4.tcp_keepalive_time significantly to see if it helps, anyway :)

**Comment by timpeeters** [comment]
After one week of running with a patched version of the plugin, I can confirm that for us, the failed scans, checkouts are no longer appearing. So for us, the patch with the retry for idempotent operations worked. I think this is a good addition to the code base because HTTP requests can fail for a large amount of reasons and having a retry for idempotent operations is safe and a common practice.

I understand that for the non-idempotent (e.g. POST) requests we might need to look for a different solution. My gut feeling is also pointing in the direction of stale connections in the pool. I'll try with a local build where I will disable connection re-use altogether, just to confirm that this is indeed the source of the problems. I'll create a separate Github issue and PR if I find out more.

However I would appreciate to treat this issue and PR for idempotent requests separately. Is that a reasonable idea?

**Comment by alanjcastonguay** [comment]
Totally: I'll make a new issue for my symptoms.

**Comment by casz** [comment]
[v2.4.6](https://github.com/jenkinsci/bitbucket-branch-source-plugin/releases/tag/cloudbees-bitbucket-branch-source-2.4.6) should be in the update center shortly

**Comment by mhworth** [comment]
Same here, thanks everyone!

Best,
Matt
