### ISSUE TITLE
Plugin Config Not Saving Across Reboots

### ISSUE THREAD

**Issue by RPGillespie6** [jenkinsci/bitbucket-branch-source-plugin#279]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [ ] Bitbucket cloud

- [x] Bitbucket server and version

### Description

- Jenkins version `2.190.1`
- Plugin version `2.5.0`
- Bitbucket server version `6.1.2`

I have an issue where Bitbucket Branch Source Plugin works perfectly until Jenkins reboots, in which case all the config is gone. 

For example, this is how I've currently configured the plugin:

![image](https://user-images.githubusercontent.com/9853156/73297409-88612d00-41d9-11ea-9f5f-9c629bc50c6a.png)

However, if Jenkins ever gets rebooted, all of this configuration is reset back to the default and BitBucket Branch starts building _every single branch_ on startup instead of just PRs as I've specified. 

Where is this configuration stored on disk? I would have thought some XML file, but grepping around I can't seem to find it.

I noticed the following in the Jenkins logs shows up every time I save config:

```
Could not register hooks for jupiter
com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 401: .
HttpResponseProxy{HTTP/1.1 401  [X-AREQUESTID: @ZQWP0Bx856x777731x0, X-ASEN: SEN-13917221, Cache-Control: no-cache, no-transform, Vary: accept-encoding,x-auserid,cookie,x-ausername,accept-encoding, WWW-Authenticate: OAuth realm="http%3A%2F%2Fgtswtbitsyslnxvm1%3A7990", X-Content-Type-Options: nosniff, Content-Type: application/json;charset=UTF-8, Transfer-Encoding: chunked, Date: Tue, 28 Jan 2020 19:16:58 GMT] org.apache.http.client.entity.DecompressingEntity@333e6936}
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:797)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getResources(BitbucketServerAPIClient.java:749)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getWebHooks(BitbucketServerAPIClient.java:675)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHook(WebhookAutoRegisterListener.java:167)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:133)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:56)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:102)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

The error says "Could not register hooks for jupiter", but webhooks are working perfectly (i.e. builds get triggered on push to BitBucket, on open PR, etc.) so I'm not sure what it is complaining about. 

Could this error be the reason config is not being saved across reboots?

**Comment by casz** [comment]
Would you mind adding a PR unit test?
See this restartable Jenkins test >
https://github.com/jenkinsci/jira-plugin/pull/195

**Comment by RPGillespie6** [comment]
Forgive me, I'm totally willing to help, but I'm not 100% sure what you are asking me to do.

If I understand you correctly, you are asking me to submit a PR to this repository that contains a unit test similar to the one you linked to that checks this behavior?

I should also note that my Jenkins instance runs as a docker container (with /var/jenkins_home mapped in as a volume) and that I do not have the JIRA plugin installed on my Jenkins instance.

**Comment by casz** [comment]
JIRA plugin was just a PR I could point to in recent memory adding a restartable jenkins unit test.

Yes, I would appreciate a unit tests PR that confirms the behavior you explained.

**Comment by casz** [comment]
@RPGillespie6 are you using job dsl by any chance?

**Comment by RPGillespie6** [comment]
No, I'm not using Job DSL. The weird thing is, after installing a plugin to purge build queue, it's no longer reproducible... So I'm wondering if some combination of plugins is causing this...

At any rate, we can close for now. I will reopen if it happens in the future and I can figure out how to reproduce reliably.
