### ISSUE TITLE
Can't find my repositories

### ISSUE THREAD

**Issue by DunklerPhoenix** [jenkinsci/bitbucket-branch-source-plugin#282]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

Heho.
I'm using Jenkins 2.204.2 with Plugin Version 2.7.
If I create a new Project and enter the credentials and the owner. The plugin can't discover any repositories.
This are the Project-Settings:
![KGRxB8Xvub](https://user-images.githubusercontent.com/1261305/73955932-7895c700-4904-11ea-963e-802ef4ffb264.png)
This is the scanresult:
![dPinLxt16c](https://user-images.githubusercontent.com/1261305/73956116-c5799d80-4904-11ea-894b-404941255a30.png)
![RC0AqDMjYx](https://user-images.githubusercontent.com/1261305/73955941-79c6f400-4904-11ea-858b-a20c906dcab5.png)

The API does not return any repositories until I remove the ownerrole parameter:
![Yuqf5l0PAC](https://user-images.githubusercontent.com/1261305/73955937-79c6f400-4904-11ea-8eb2-ee4bfa6faf70.png)

I'm listed as owner 
`"owner": {"display_name": "Marco Eckert", "uuid": "{eece1fb6-57c6-4714-bda5-1d950e457d92}",`
But even if I use my uuid the result is empty every time.

My Bitbucket Account is an Atlassian Account. What can I do? Should I create a team and move everything?

**Comment by DunklerPhoenix** [comment]
No no No my cute lil bot. Its still active

**Comment by DunklerPhoenix** [comment]
Last time then i'll give up xD

**Comment by kshultzCB** [comment]
@DunklerPhoenix - Assuming [this](https://bitbucket.org/RogueThorn/) is your Bitbucket team, I'm able to correctly discover [the one public repository shown there](https://bitbucket.org/RogueThorn/utopia-mining-bot/src/master/). I actually didn't even need any credentials:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/21689198/86627422-4e6d3180-bf96-11ea-9881-06633a9515bd.png">

Do you have any administrative alerts in your Jenkins, especially regarding plugin versions not being able to load? I've tried your described version (Jenkins core 2.204.2) using a simple, local `java -jar jenkins.war` setup on my laptop, and had a lot of trouble getting some pretty core plugins to load with that version. Many are asking for an update to Jenkins core 2.204.6:

```
java.io.IOException: Snakeyaml API Plugin version 1.26.4 failed to load.
 - You must update Jenkins from version 2.204.2 to version 2.204.6 or later to run this plugin.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:932)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:929)
Caused: java.io.IOException: Failed to install snakeyaml-api plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:942)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2082)
Caused: java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2086)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1773)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)
	at java.lang.Thread.run(Thread.java:819)
2020-07-06 18:41:42.273+0000 [id=116]	INFO	h.model.UpdateCenter$DownloadJob#run: Starting the installation of jackson2-api on behalf of admin
2020-07-06 18:41:42.436+0000 [id=116]	INFO	h.m.UpdateCenter$UpdateCenterConfiguration#download: Downloading jackson2-api
2020-07-06 18:41:42.812+0000 [id=116]	SEVERE	h.model.UpdateCenter$DownloadJob#run: Failed to install jackson2-api
java.io.IOException: Jackson 2 API Plugin version 2.11.1 failed to load.
 - Snakeyaml API Plugin version 1.26.4 failed to load. Fix this plugin first.
	at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:932)
	at hudson.PluginManager.dynamicLoad(PluginManager.java:929)
Caused: java.io.IOException: Failed to install jackson2-api plugin
	at hudson.PluginManager.dynamicLoad(PluginManager.java:942)
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2082)
Caused: java.io.IOException: Failed to dynamically deploy this plugin
	at hudson.model.UpdateCenter$InstallationJob._run(UpdateCenter.java:2086)
	at hudson.model.UpdateCenter$DownloadJob.run(UpdateCenter.java:1773)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.AtmostOneThreadExecutor$Worker.run(AtmostOneThreadExecutor.java:111)
	at java.lang.Thread.run(Thread.java:819)
```

Without Jackson correctly loading, Bitbucket won't work because [that's a dependency](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/621abadb6017f4f39af3aba0ff7ba6542ae0e6d1/pom.xml#L118-L122).

In my case, after updating to jenkins.war at [2.204.6](http://mirrors.jenkins.io/war-stable/2.204.6/), all of those problems went away. I was able to find your repository again, still without using any credentials at all.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/21689198/86628933-9ee58e80-bf98-11ea-87b6-e2f56fc1d8d9.png">

**Comment by DunklerPhoenix** [comment]
Thanks for your Answer. Actually I don't have jenkins running anymore, because the server where it was installed doesn't exist anymore. 
I'll reinstall it the next days and try again. :D

**Comment by flockoftanks** [comment]
@DunklerPhoenix I did find that you can't just have access to the repo, you actually have to be in the "Team" or "Workspace" in which the repo lives. Without being in the team, you'll only see the repos in your personal team (ooof Bitbucket) which probably = 0.

I'm working on my Bitbucket admins to get added to the team that I would like to access to test this theory.

**Comment by DunklerPhoenix** [comment]
Yet it's working with the newer version ^^
Thank you
