### ISSUE TITLE
X-Event-Key HTTP header invalid: repo:commit_status_created

### ISSUE THREAD

**Issue by chb0github** [jenkinsci/bitbucket-branch-source-plugin#285]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version

- [x] Bitbucket cloud

- [ ] Bitbucket server and version

### Description

- Jenkins version: 2.204.2
- Plugin version: 2.7.0
- Using BB Cloud

Dead simple problem and fix. The code is out-of-sync with the events available from BB cloud:

```
java.lang.Exception: X-Event-Key HTTP header invalid: repo:commit_status_created
	at org.kohsuke.stapler.HttpResponses.error(HttpResponses.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.BitbucketSCMSourcePushHookReceiver.doNotify(BitbucketSCMSourcePushHookReceiver.java:88)
	at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
```
Tracks right to this code:

```java
HookEventType type = HookEventType.fromString(eventKey);
        if (type == null) {
            LOGGER.info("Received unknown Bitbucket hook: " + eventKey + ". Skipping.");
            return HttpResponses.error(HttpServletResponse.SC_BAD_REQUEST, "X-Event-Key HTTP header invalid: " + eventKey);
        }
```

I can easily fix this if I know the PR will get merged. I see some PRs have been sitting a while.

**Comment by casz** [comment]
@chb0github your concern is unwarranted: https://github.com/jenkinsci/bitbucket-branch-source-plugin/pulse/monthly

**Comment by jetersen** [comment]
Still awaiting a PR 😅

**Comment by chb0github** [comment]
Yeah, yeah! 😄 

Not throwing the error is easy enough - what to do with the payload once received is a whole other matter. 

But, in the what-it's-worth department, I did fix another jenkins plugin and that one DID get accepted
