### ISSUE TITLE
Implement connection retry functionality

### ISSUE THREAD

**Issue by ikari7789** [jenkinsci/bitbucket-branch-source-plugin#300]
### Your checklist for this issue

- [x] Jenkins version

- [x] Plugin version 

- [ ] Bitbucket cloud

- [x] Bitbucket server and version

### Description

Jenkins version: 2.230
Plugin version: 2.7.0
Bitbucket server and version: 5.16.11

I'd like to request some level of retry logic be implemented to avoid fatal shutdowns during organization scans. Any exceptions thrown during the Organization Folder scan will cause it to stop immediately requiring it to be run again from the top. This means if you're facing any kind of issue on one repository in particular or some other network-related issue, you'll need to retry the entire scan, again and again, until it can (hopefully) make a single pass through everything.

In our particular use case, we constantly receive this `SSL peer shut down incorrectly` error and it makes the plugin basically unusable. I'm not entirely sure of the cause of the issue neither and I'm not in a position to be able to fix it on the Bitbucket server as I'm just a consumer as part of a larger organization.

```
ERROR: [Thu Apr 09 10:10:02 JST 2020] Could not fetch sources from navigator com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator@5ecaf6e2
java.io.EOFException: SSL peer shut down incorrectly
	at sun.security.ssl.InputRecord.read(InputRecord.java:505)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
Caused: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:994)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.upgrade(DefaultHttpClientConnectionOperator.java:191)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.upgrade(PoolingHttpClientConnectionManager.java:390)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:428)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:812)
Caused: java.io.IOException: Communication error for url: /rest/api/1.0/projects/<tag>/repos/<repository>
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:842)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRepository(BitbucketServerAPIClient.java:435)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveTags(BitbucketSCMSource.java:768)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:597)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:327)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:263)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1405)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1420)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:254)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:204)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator.visitSources(BitbucketSCMNavigator.java:501)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:488)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:277)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:164)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:969)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
```

**Comment by jetersen** [comment]
@ikari7789 you should really look into configuring the SSL timeout on the server instead.

**Comment by jetersen** [comment]
Are you using tomcat for SSL termination? If so I suggest using another service such as nginx or haproxy or similar

**Comment by ikari7789** [comment]
@jetersen Are you referring to the Bitbucket Server's SSL timeout or the Jenkins servers? In the case of the Bitbucket Server, I have no control over how it's configured. I'm just a consumer within my company and they have some very weird configuration to handle our total user load (over 2000 users).

Even still, suggesting to fix this kind of network disconnect issue in the server-side seems like the wrong suggestion considering the fact that there's no requirement that the server you are connecting to is guaranteed to be something you are in control of. If I was receiving a similar issue via Bitbucket Cloud, I'd just as likely want it to be able to complete to the end (with errors) than to constantly fail part way through.

**Comment by jetersen** [comment]
SSL hand shake should never timeout its a first for me to see this issue connecting to bitbucket. Again fix your bitbucket server.

**Comment by jetersen** [comment]
If you want to get to the bottom of the issue for Jenkins I suggest adding `-Djavax.net.debug=ssl` and grab the logs when it fails for Bitbucket.
