### ISSUE TITLE
Bug on 2.8.0: Exception on reading the Jenkins settings for Bitbucket Cloud

### ISSUE THREAD

**Issue by michelzanini** [jenkinsci/bitbucket-branch-source-plugin#311]
Hi,

I am duplicating this issue from:
https://issues.jenkins-ci.org/browse/JENKINS-62180

I am getting an exception when I open Manage Jenkins -> Configuration after installing the newest version of Bitbucket Cloud 2.8.0.

```
Error while serving
https://system-dev-jenkins.build.mttnow.com/descriptorByName/com.cloudbees.
jenkins.plugins.bitbucket.endpoints.BitbucketCloudEndpoint/
fillCredentialsIdItems com.amazonaws.services.ecr.model.AmazonECRException: The
security token included in the request is invalid (Service: AmazonECR; Status
Code: 400; Error Code: UnrecognizedClientException; Request ID:
bb63ccfc-1924-475f-bf3e-9d219f70d6ac) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(
AmazonHttpClient.java:1799) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleServiceErrorResponse(
AmazonHttpClient.java:1383) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(
AmazonHttpClient.java:1359) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(
AmazonHttpClient.java:1139) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.
java:796) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(
AmazonHttpClient.java:764) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.
java:738) at
com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.
java:698) at
com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(
AmazonHttpClient.java:680) at
com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:544) at
com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:524) at
com.amazonaws.services.ecr.AmazonECRClient.doInvoke(AmazonECRClient.java:2383)
at com.amazonaws.services.ecr.AmazonECRClient.invoke(AmazonECRClient.java:2350)
at com.amazonaws.services.ecr.AmazonECRClient.invoke(AmazonECRClient.java:2339)
at
com.amazonaws.services.ecr.AmazonECRClient.executeGetAuthorizationToken(
AmazonECRClient.java:1166) at
com.amazonaws.services.ecr.AmazonECRClient.getAuthorizationToken(AmazonECRClient
.java:1136) at
com.cloudbees.jenkins.plugins.amazonecr.AmazonECSRegistryCredential.getPassword(
AmazonECSRegistryCredential.java:131) at
com.cloudbees.jenkins.plugins.bitbucket.api.credentials.
BitbucketOAuthCredentialMatcher.matches(BitbucketOAuthCredentialMatcher.java:25)
at
com.cloudbees.plugins.credentials.matchers.AnyOfMatcher.matches(AnyOfMatcher.
java:67) at
com.cloudbees.plugins.credentials.CredentialsProvider.getCredentialIds(
CredentialsProvider.java:1196) at
com.cloudbees.plugins.credentials.CredentialsProvider.listCredentials(
CredentialsProvider.java:484) at
com.cloudbees.plugins.credentials.common.AbstractIdCredentialsListBoxModel.
includeMatchingAs(AbstractIdCredentialsListBoxModel.java:499) at
com.cloudbees.jenkins.plugins.bitbucket.endpoints.
AbstractBitbucketEndpointDescriptor.doFillCredentialsIdItems(
AbstractBitbucketEndpointDescriptor.java:61) at
java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:627) at
org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396) Caused:
java.lang.reflect.InvocationTargetException at
org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:400)
```

This is the screen shot:
![Screen Shot 2020-05-06 at 14 24 01](https://user-images.githubusercontent.com/4479787/82058626-606bdb80-969b-11ea-9965-df434532bc00.png)

I believe it has something to do with a Amazon credentials provider and a few of the credentials I might have of that type, but not sure why this is happening.

It is related to the new OAuth feature - as the exception happens on BitbucketOAuthCredentialMatcher.

Thanks.

**Comment by michelzanini** [comment]
@kurddt

**Comment by randomvoids** [comment]
This issue is causing the configuration sections of other plugins, such as the ec2-plugin, to not work correctly too. It breaks the dropdowns. Hopefully the PR 329 fix is merged and pushed out soon.

**Comment by bitwiseman** [comment]
@randomvoids 
You can try out #329 now by install this incremental build: https://repo.jenkins-ci.org/incrementals/org/jenkins-ci/plugins/cloudbees-bitbucket-branch-source/2.9.2-rc646.0647f1a48615/

I would not suggest you install it on production, but getting more information on the behavior and user experience would be useful.

**Comment by bitwiseman** [comment]
#329 was merged.  Closing.
