### ISSUE TITLE
WebHook registration fails with v. 2.9.1 of plugin towards BitBucket Server 5.16.11

### ISSUE THREAD

**Issue by mortenkri** [jenkinsci/bitbucket-branch-source-plugin#352]
### Your checklist for this issue

- [x] Jenkins version: CloudBees Jenkins Distribution 2.235.4.1

- [x] Plugin version: 2.9.1

- [x] Bitbucket cloud: NA

- [x] Bitbucket server and version: 5.16.11

### Description

We are using CloudBees Jenkins Distribution (v 2.235.4.1) which enforces version 2.9.1 of this plugin. Towards BitBucket Server version 5.16.11, the WebHook registration fails with HTTP Status 400 (Bad Request):

```
2020-08-17 11:27:03.283+0000 [id=350]	WARNING	c.c.j.p.b.h.WebhookAutoRegisterListener$1#doRun: Could not register hooks for XXX
--
  | com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 400: .
  | HttpResponseProxy{HTTP/1.1 400  XXXX
  | at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.doRequest(BitbucketServerAPIClient.java:1069)
  | at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.putRequest(BitbucketServerAPIClient.java:1080)
  | at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.updateCommitWebHook(BitbucketServerAPIClient.java:651)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHook(WebhookAutoRegisterListener.java:181)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:133)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:56)
  | at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:102)
  | at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:91)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  | at java.lang.Thread.run(Thread.java:748)

```

**Comment by bitwiseman** [comment]
I don't have the bandwidth to make the changes right now, but the PR #332 I submitted can be used as a template for adding a "5.x" setting. It is likely that another of the hooks being requested are not present in 5.x.

**Comment by cybe** [comment]
We use Bitbucket 5.16.0 and #326 fixed this issue for us.

@mortenkri are you sure you selected the correct Server Version in the global configuration screen?

**Comment by mortenkri** [comment]
@bitwiseman @cybe My bad! I was unaware of the Server Version config option globally. Since it default to v 7 it failed. Setting it to v 6 did the trick. Sorry about that.
