### ISSUE TITLE
Could not fetch sources from navigator com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator

### ISSUE THREAD

**Issue by siorellana** [jenkinsci/bitbucket-branch-source-plugin#364]
Hello everyone.
We are seeing a very rare error in our new implementation of Jenkins with Bitbucket. 
Randomly the scan of the repositories fails with a **_Time Out_** error, but we already discarting any issue on the network, OS, DNS and Bitbucket server and this is blowing my mind.

## Your checklist for this issue

- [X] Jenkins version - 2.235.5
- [X] Plugin version - 2.7.0 but tested also the last 2.9.2
- [X] Bitbucket server and version - Bitbucket 5.9 Datacenter

## Description
When a new scan of a project is triggered, its randomly fails with the following message:
```
Connecting to https://repo.mycompany.com using jenkins-srv/******
Repository type: Git
Looking up CLOUDREPO/proxypasslocal for branches
Checking branch master from CLOUDREPO/proxypasslocal
ERROR: [Wed Sep 02 16:11:22 UTC 2020] Could not fetch sources from navigator com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator@4485b2e2
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:368)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
Caused: org.apache.http.conn.ConnectTimeoutException: Connect to coderepo.appslatam.com:443 [coderepo.appslatam.com/35.227.214.102] failed: connect timed out
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:374)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequestStatus(BitbucketServerAPIClient.java:961)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.checkPathExists(BitbucketServerAPIClient.java:487)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource$BitbucketProbeFactory$1.exists(BitbucketSCMSource.java:1478)
	at jenkins.scm.api.SCMSourceCriteria$Probe.stat(SCMSourceCriteria.java:99)
	at org.jenkinsci.plugins.workflow.multibranch.WorkflowBranchProjectFactory$1.isHead(WorkflowBranchProjectFactory.java:74)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:342)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveBranches(BitbucketSCMSource.java:748)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:589)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:373)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:327)
	at jenkins.branch.MultiBranchProjectFactory$BySCMSourceCriteria.recognizes(MultiBranchProjectFactory.java:261)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.recognizes(OrganizationFolder.java:1468)
	at jenkins.branch.OrganizationFolder$SCMSourceObserverImpl$1.complete(OrganizationFolder.java:1483)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:254)
	at jenkins.scm.api.trait.SCMNavigatorRequest.process(SCMNavigatorRequest.java:204)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMNavigator.visitSources(BitbucketSCMNavigator.java:501)
	at jenkins.branch.OrganizationFolder.computeChildren(OrganizationFolder.java:542)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:278)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:165)
	at jenkins.branch.OrganizationFolder$OrganizationScan.run(OrganizationFolder.java:1033)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
[Wed Sep 02 16:11:22 UTC 2020] Finished organization scan. Scan took 1 min 22 sec
FATAL: Failed to recompute children of CLOUDREPO
````
The weird thing is that we have actually other Jenkins server, with the same configuration and it work without issues. The unique difference is in the version of the Jenkins (2.190.1) both are on Kubernetes.

## Discarting tests
- In order to discard any issue of network, we have run the same API calls inside of the container of the Jenkins and this work fine.
- We have discarted any issue with the repositories configuration or permissions and numbers of repositories.
- We have tested all the configuration variables like version of the plugins and native or plugin mode. But the error still persist.

## References
- https://issues.jenkins-ci.org/browse/JENKINS-48019

Again, this is randomly, there is not a pattern, it fail in different repositories and with different time of processing, so we have no idea how to continue with this.
Thanks for your help.

**Comment by siorellana** [comment]
Finally, this is a GCP CloudNAT misconfiguration that is causing a Drop of the connections.
For reference, for each branch on each repository, Jenkins create a new connection to Bitbucket. In this case, Jenkins send 1.580 requests, so the CloudNAT of the GCP Platform must be configured to support this connections volume.
