### ISSUE TITLE
ERROR: Could not do lightweight checkout

### ISSUE THREAD

**Issue by EshaBangar** [jenkinsci/bitbucket-branch-source-plugin#405]
### Your checklist for this issue

- [x ] Jenkins version :CloudBees 2.235.5.1

- [ x] Plugin version : 2.9.1

- [ ] Bitbucket cloud

- [x ] Bitbucket server and version : Bitbucket data center v7.5.0

### Description
I migrated bitbucket from v6.9.1 to v7.5.0 and post bitbucket upgrade , I see frequent errors in PR for multibranch jenkins pipelines :

_Branch event
ERROR: Could not do lightweight checkout, falling back to heavyweight
java.io.FileNotFoundException: URL: /rest/api/1.0/projects/OP/repos/ovn-mp-common/browse/Jenkinsfile?at=pull-requests%2F487%2Fmerge&start=0&limit=500
at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:854)
at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getFileContent(BitbucketServerAPIClient.java:1149)
at com.cloudbees.jenkins.plugins.bitbucket.filesystem.BitbucketSCMFile.content(BitbucketSCMFile.java:98)
at jenkins.scm.api.SCMFile.contentAsString(SCMFile.java:335)
at org.jenkinsci.plugins.workflow.multibranch.SCMBinder.create(SCMBinder.java:107)
at org.jenkinsci.plugins.workflow.job.WorkflowRun.run(WorkflowRun.java:309)
at hudson.model.ResourceController.execute(ResourceController.java:97)
at hudson.model.Executor.run(Executor.java:428)_

I was reading through various articles and found that Lightweight checkout fails in Bitbucket Server 7.0; refs/pull-requests/*/merge does not exist any more.

links to articles:
https://issues.jenkins.io/browse/JENKINS-49353
https://issues.jenkins.io/browse/JENKINS-61493
https://jira.atlassian.com/browse/BSERV-12284

Do you have any fix for it ? or do you know if there is any workaround?
How shall we use "bitbucket-branch-source-plugin" to scan entire bitbucket project/org in jenkins. All PR fails since bitbucket removed the refs for diff/commit in the PR.

**Comment by bitwiseman** [comment]
I think this is the same as #336 and the message at the top of https://issues.jenkins.io/browse/JENKINS-61493 accurately describes the problem.  NOTE: your PRs failing is a separate issue, have you set your server version in your endpoint and enabled both checkboxes?
