### ISSUE TITLE
java.lang.Exception: X-Event-Key HTTP header invalid: pr:comment:added

### ISSUE THREAD

**Issue by stevemayster** [jenkinsci/bitbucket-branch-source-plugin#488]
### Version report

Jenkins and plugins versions report:

Jenkins version 2.206
Plugin version 2.6.0

- What Operating System are you using (both controller, and any agents involved in the problem)?

Windows Server 2016

### Reproduction steps

Configure Bitbucket and Jenkins integration via web hook using url jenkins.host.com/bitbucket-scmsource-hook/notify?server_url=
### Results
After commit in pull request got error 400

Expected result:

Pull request commit will triggering Jenkins multi-branch project

Actual result:

Got error
java.lang.Exception: X-Event-Key HTTP header invalid: pr:comment:added
	at org.kohsuke.stapler.HttpResponses.error(HttpResponses.java:83)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.BitbucketSCMSourcePushHookReceiver.doNotify(BitbucketSCMSourcePushHookReceiver.java:88)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:396)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:408)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:212)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:145)
	at org.kohsuke.stapler.MetaClass$11.doDispatch(MetaClass.java:535)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.MetaClass$9.dispatch(MetaClass.java:456)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:747)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:878)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:676)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:760)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:154)
	at jenkins.security.ResourceDomainFilter.doFilter(ResourceDomainFilter.java:76)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at jenkins.telemetry.impl.UserLanguages$AcceptLanguageFilter.doFilter(UserLanguages.java:128)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:151)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:157)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.BitbucketSCMSourcePushHookReceiver.process(BitbucketSCMSourcePushHookReceiver.java:59) .........omitted

**Comment by KalleOlaviNiemitalo** [comment]
"pr:comment:added" and other types described in [Event payload](<https://confluence.atlassian.com/bitbucketserver0715/event-payload-1082270520.html> "Event payload | Bitbucket Data Center and Server 7.15 | Atlassian Documentation") could be added to (HookEventType.java)[https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.9.11/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/HookEventType.java), I guess. However…

* What configured Bitbucket Server to send this event to Jenkins? [WebhookConfiguration.java](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.9.11/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/WebhookConfiguration.java) does not include this event type when it configures the webhook.
* Do you expect Jenkins to build the pull request when it receives this event?

**Comment by stevemayster** [comment]
Hello,KalleOlaviNiemitalo
Thank you to point me to right direction
Now i'm installed Post Webhook for Bitbucket and get another error( 
I'm follow to this instruction https://support.cloudbees.com/hc/en-us/articles/115000053051
which says :
The option Manage Hooks may be enabled for a specific endpoint under Manage Jenkins > Configure System > Bitbucket Endpoints to allow Jenkins to automatically register webhooks to that endpoint. This is the recommended, quicker, easiest configuration.
But after i trigger Scan Organization folder i see error in log 
Could not register hooks for BB_Project/ibso_bspb_local
com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 401: .
HttpResponseProxy{HTTP/1.1 401  [Cache-Control: private, Expires: Thu, 01 Jan 1970 00:00:00 GMT, X-AREQUESTID: @OZ0X0Rx960x131070x0, X-ASEN: SEN-19665966, Cache-Control: no-transform, X-Content-Type-Options: nosniff, Vary: Accept, WWW-Authenticate: OAuth realm="https%3A%2F%2Fbitbucket", Content-Type: application/xml, Transfer-Encoding: chunked, Date: Fri, 01 Oct 2021 13:00:35 GMT, Keep-Alive: timeout=20, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/xml,Chunked: true]}}
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:827)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getWebHooks(BitbucketServerAPIClient.java:676)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHook(WebhookAutoRegisterListener.java:167)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:133)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:56)
	at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:102)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:70)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Bitbucket and Jenkins on the same server, user used in configuration have Admin role.

**Comment by stevemayster** [comment]
So i open bitbucket logs and see this

GET /rest/webhook/1.0/projects/Project/repos/test/configurations HTTP/1.1" | "" "Apache-HttpClient/4.5.10 (Java/1.8.0_144)" | 401 | 0 | 174 | - | 13 |
But i don't understand why plugin try authenticate without passing a credential.
