### ISSUE TITLE
Webhook registration fails on Bitbucket 6.10

### ISSUE THREAD

**Issue by stevemayster** [jenkinsci/bitbucket-branch-source-plugin#491]
### Version report

Jenkins and plugins versions report:
Jenkins 2.314
Bitbucket branch source plugin 2.911
Bitbucket server version 6.10.10

- What Operating System are you using (both controller, and any agents involved in the problem)?

Windows 2016

### Reproduction steps
Installed Post Webhook for Bitbucket
In Branch source plugin choosed server version 6.X
Manage Webhooks checkbox ticked
Added new bitbucket/teams multibranch job and configured
Started Scan Organization Folder

### Results

Expected result:

Jenkins autoregister in Post Webhook

Actual result:
Webhook not registered in Bitbucket with HTTP 401

Bitbucket logs

10.55.34.20| https |   | - | 2021-10-06 11:26:47,374 | "GET /rest/api/1.0/projects/TEST HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https | | - | 2021-10-06 11:26:47,390 | "GET /rest/api/1.0/projects/TEST HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 218 | - | 11 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,421 | "GET /rest/api/1.0/projects/TEST HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,436 | "GET /rest/api/1.0/projects/TEST HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 218 | - | 10 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,453 | "GET /rest/api/1.0/projects/TEST/repos HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,468 | "GET /rest/api/1.0/projects/TEST/repos HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 3695 | - | 18 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,499 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,515 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 625 | - | 18 | - |
10.55.34.20| https | | - | 2021-10-06 11:26:47,546 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https | | - | 2021-10-06 11:26:47,561 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 625 | - | 11 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,577 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/branches HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,640 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/branches HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 2468 | - | 56 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,655 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/pull-requests HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,686 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/pull-requests HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 62 | - | 16 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,702 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/browse/Jenkinsfile HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,796 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/browse/Jenkinsfile HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 200 | 0 | 1433 | - | 94 | - |
10.55.34.20| https | | - | 2021-10-06 11:26:47,827 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/commits/47cc269e9bc18df251f19d2b2ab650abf87a1123 HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" |
- | - | - | - | - | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,890 | "GET /rest/api/1.0/projects/TEST/repos/test_project_local/commits/47cc269e9bc18df251f19d2b2ab650abf87a1123 HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" |
200 | 0 | 1137 | - | 61 | - |
10.55.34.20| https |  | - | 2021-10-06 11:26:47,937 | "GET /rest/webhook/1.0/projects/TEST/repos/test_project_local/configurations HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | - | - | - | - | - | - |
**10.55.34.20| https |  | - | 2021-10-06 11:26:47,937 | "GET /rest/webhook/1.0/projects/TEST/repos/test_project_local/configurations HTTP/1.1" | "" "Apache-HttpClient/4.5.13 (Java/1.8.0_144)" | 401 | 0 | 174 | - | 12 | - |**

Jenkins show an error

oct 06, 2021 11:26:47 AM WARNING com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1 doRun
Could not register hooks for Test/test_project_local
com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 401: .
HttpResponseProxy{HTTP/1.1 401  [Cache-Control: private, Expires: Thu, 01 Jan 1970 00:00:00 GMT, X-AREQUESTID: , X-ASEN: SEN-19665966, Cache-Control: no-transform, X-Content-Type-Options: nosniff, Vary: Accept, WWW-Authenticate: OAuth realm="https%3A%2F%2Fbitbucket", Content-Type: application/xml, Transfer-Encoding: chunked, Date: Wed, 06 Oct 2021 08:26:47 GMT, Keep-Alive: timeout=20, Connection: keep-alive] ResponseEntityProxy{[Content-Type: application/xml,Chunked: true]}}
        at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:883)
        at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getWebHooks(BitbucketServerAPIClient.java:732)
        at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHook(WebhookAutoRegisterListener.java:167)
        at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.registerHooks(WebhookAutoRegisterListener.java:133)
        at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener.access$000(WebhookAutoRegisterListener.java:56)
        at com.cloudbees.jenkins.plugins.bitbucket.hooks.WebhookAutoRegisterListener$1.doRun(WebhookAutoRegisterListener.java:102)
        at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:90)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

User have admin privileges

**Comment by stevemayster** [comment]
I figured it out.
So protocol in Bitbucket server must be set right
http://bitbucket and https://bitbucket is a BIG difference.
