### ISSUE TITLE
LFS Endpoint not being set (Bitbucket OAuth) causing LFS pull to fail

### ISSUE THREAD

**Issue by frankvHoof93** [jenkinsci/bitbucket-branch-source-plugin#593]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  
  ```text
  Jenkins: 2.332.2
OS: Linux - 5.10.16.3-microsoft-standard-WSL2
---
ace-editor:1.1
ant:475.vf34069fef73c
antisamy-markup-formatter:2.7
apache-httpcomponents-client-4-api:4.5.13-1.0
atlassian-bitbucket-server-integration:3.2.1
authentication-tokens:1.4
bitbucket:223.vd12f2bca5430
bitbucket-oauth:0.12
bitbucket-pullrequest-builder:1.5.0
bitbucket-pullrequests-filter:0.1.0
bitbucket-push-and-pull-request:2.8.1
blueocean:1.25.3
blueocean-autofavorite:1.2.5
blueocean-bitbucket-pipeline:1.25.3
blueocean-commons:1.25.3
blueocean-config:1.25.3
blueocean-core-js:1.25.3
blueocean-dashboard:1.25.3
blueocean-display-url:2.4.1
blueocean-events:1.25.3
blueocean-git-pipeline:1.25.3
blueocean-github-pipeline:1.25.3
blueocean-i18n:1.25.3
blueocean-jira:1.25.3
blueocean-jwt:1.25.3
blueocean-personalization:1.25.3
blueocean-pipeline-api-impl:1.25.3
blueocean-pipeline-editor:1.25.3
blueocean-pipeline-scm-api:1.25.3
blueocean-rest:1.25.3
blueocean-rest-impl:1.25.3
blueocean-web:1.25.3
bootstrap4-api:4.6.0-4
bootstrap5-api:5.1.3-6
bouncycastle-api:2.26
branch-api:2.1046.v0ca_37783ecc5
build-timeout:1.20
caffeine-api:2.9.3-65.v6a_47d0f4d1fe
checks-api:1.7.3
cloudbees-bitbucket-branch-source:765.v5a_2d6a_23c01d
cloudbees-folder:6.714.v79e858ef76a_2
command-launcher:81.v9c2cb_cb_db_392
config-file-provider:3.9.0
credentials:1087.1089.v2f1b_9a_b_040e4
credentials-binding:523.vd859a_4b_122e6
discord-notifier:206.vee9f4569ee63
display-url-api:2.3.6
docker-build-step:2.8
docker-commons:1.19
docker-compose-build-step:1.0
docker-java-api:3.2.13-37.vf3411c9828b9
docker-plugin:1.2.9
docker-slaves:1.0.7
docker-workflow:1.28
durable-task:496.va67c6f9eefa7
echarts-api:5.3.2-1
email-ext:2.88
external-monitor-job:191.v363d0d1efdf8
favorite:2.4.1
font-awesome-api:6.0.0-1
git:4.11.1
git-client:3.11.0
git-server:1.10
github:1.34.3
github-api:1.303-400.v35c2d8258028
github-branch-source:1598.v91207e9f9b_4a_
google-oauth-plugin:1.0.6
google-play-android-publisher:4.2
gradle:1.38
handlebars:3.0.8
handy-uri-templates-2-api:2.1.8-22.v77d5b_75e6953
htmlpublisher:1.30
jackson2-api:2.13.2.20220328-273.v11d70a_b_a_1a_52
javadoc:217.v905b_86277a_2a_
javax-activation-api:1.2.0-3
javax-mail-api:1.6.2-6
jaxb:2.3.0.1
jdk-tool:1.5
jenkins-design-language:1.25.3
jira:3.7.1
jjwt-api:0.11.2-71.v2722b_b_06a_2a_f
jnr-posix-api:3.1.7-3
job-dsl:1.79
jquery:1.12.4-1
jquery-detached:1.2.1
jquery3-api:3.6.0-3
jsch:0.1.55.2
junit:1.60
ldap:2.9
locale:144.v1a_998824ddb_3
lockable-resources:2.14
mailer:414.vcc4c33714601
mapdb-api:1.0.9.0
matrix-auth:3.1.1
matrix-project:771.v574584b_39e60
maven-plugin:3.18
mercurial:2.16
momentjs:1.1.1
oauth-credentials:0.5
okhttp-api:4.9.3-105.vb96869f8ac3a
pam-auth:1.8
pipeline-build-step:2.18
pipeline-github-lib:36.v4c01db_ca_ed16
pipeline-graph-analysis:195.v5812d95a_a_2f9
pipeline-input-step:448.v37cea_9a_10a_70
pipeline-milestone-step:101.vd572fef9d926
pipeline-model-api:2.2077.vc78ec45162f1
pipeline-model-definition:2.2077.vc78ec45162f1
pipeline-model-extensions:2.2077.vc78ec45162f1
pipeline-rest-api:2.24
pipeline-stage-step:293.v200037eefcd5
pipeline-stage-tags-metadata:2.2077.vc78ec45162f1
pipeline-stage-view:2.24
pipeline-utility-steps:2.12.0
plain-credentials:1.8
plugin-util-api:2.16.0
popper-api:1.16.1-3
popper2-api:2.11.5-1
preSCMbuildstep:0.3
pubsub-light:1.16
resource-disposer:0.19
run-condition:1.5
scm-api:608.vfa_f971c5a_a_e9
script-security:1158.v7c1b_73a_69a_08
snakeyaml-api:1.30.1
sonar:2.14
sse-gateway:1.25
ssh-credentials:277.v95c2fec1c047
ssh-slaves:1.814.vc82988f54b_10
sshd:3.228.v4c9f9e652c86
structs:318.va_f3ccb_729b_71
subversion:2.15.4
timestamper:1.17
token-macro:293.v283932a_0a_b_49
trilead-api:1.57.v6e90e07157e1
unity3d-plugin:1.3
variant:1.4
windows-slaves:1.8
workflow-aggregator:2.7
workflow-api:1144.v61c3180fa_03f
workflow-basic-steps:948.v2c72a_091b_b_68
workflow-cps:2689.v434009a_31b_f1
workflow-cps-global-lib:570.v21311f4951f8
workflow-durable-task-step:1130.v8fd69d0b_8857
workflow-job:1180.v04c4e75dce43
workflow-multibranch:712.vc169a_1387405
workflow-scm-step:399.v9b_8f4da_65061
workflow-step-api:625.vd896b_f445a_f8
workflow-support:819.v37d707a_71d9b_
ws-cleanup:0.42
   ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Running in Docker.
Jenkins-Master: jenkinsci/blueocean:latest
Node doing the Checkout: jenkins/agent:latest (custom dockerfile used to update LFS to latest version)

Versions on Node:
git version 2.30.2
git-lfs/3.1.4 (GitHub; linux amd64; go 1.17.8)

### Reproduction steps

1. Added a multi-branch pipeline using Bitbucket OAuth (Repository discovered via Credentials & Owner)
2. Attempted to do a 'checkout scm'-step in the first stage of my pipeline
3. Checkout fails if LFS-files are present in the repository

### Expected Results

LFS files are pulled from the relevant LFS-repository for the Bitbucket-Repo set for the jenkins-project

### Actual Results

Pulling the files fails with the following error:
```
batch request: missing protocol: "<unknown>"
Failed to fetch some objects from '<unknown>'
```

### Anything else?

It looks like the 'endpoint' is not being set in the LFS-environment
I have tried pulling with --skip-smudge before the `checkout scm` and doing a manual `git lfs pull`, with the same result.
Tried both with & without the 'Git LFS pull after checkout'-behaviour in the project-configuration (on jenkins). The result is always the same: Missing protocol: "unknown"

Output of logging-attempt below (tokens & identifiers replaced):
```
+ git lfs install --skip-smudge
Git LFS initialized.
```

```
+ git lfs env
```
(Skipped copying empty config, this is pre-checkout)

```
Check out from version control:
The recommended git tool is: NONE
using credential Bitbucket_OAuth
Cloning the remote Git repository
Cloning with configured refspecs honoured and without tags
Cloning repository [https://x-token-auth:{**TOKEN**}@bitbucket.org/**USER**/**REPO**.git](https://x-token-auth:**TOKEN**@bitbucket.org/**USER**/**REPO**.git)
 > git init /home/jenkins/agent/workspace/BuildTest_master # timeout=10
Fetching upstream changes from https://x-token-auth@bitbucket.org/**USER**/**REPO**.git
 > git --version # timeout=10
 > git --version # 'git version 2.30.2'
using GIT_ASKPASS to set credentials OAuth-Credentials for Bitbucket Repositories
 > git fetch --no-tags --force --progress -- [https://x-token-auth:{**TOKEN**}@bitbucket.org/**USER**/**REPO**.git](https://x-token-auth:**TOKEN**@bitbucket.org/**USER**/**REPO**.git) +refs/heads/master:refs/remotes/origin/master # timeout=10
Avoid second fetch
Checking out Revision ec926cd8e6735a2451a44354d052bbb97efb7713 (master)
 > git config remote.origin.url [https://x-token-auth:{**TOKEN**}@bitbucket.org/**USER**/**REPO**.git](https://x-token-auth:**TOKEN**@bitbucket.org/**USER**/**REPO**.git) # timeout=10
 > git config --add remote.origin.fetch +refs/heads/master:refs/remotes/origin/master # timeout=10
 > git config core.sparsecheckout # timeout=10
 > git checkout -f ec926cd8e6735a2451a44354d052bbb97efb7713 # timeout=10
Commit message: "no message"
First time build. Skipping changelog.
[Bitbucket] Notifying commit build result
Can not determine Jenkins root URL or Jenkins URL is not a valid URL regarding Bitbucket API. Commit status notifications are disabled until a root URL is configured in Jenkins global configuration. 
IllegalStateException: Jenkins URL cannot start with http://localhost/
```

I believe the issue is here.. Shouldn't "Endpoint" be filled at this point?
```
+ git lfs env
git-lfs/3.1.4 (GitHub; linux amd64; go 1.17.8)
git version 2.30.2
Endpoint=<unknown> (auth=none)
LocalWorkingDir=/home/jenkins/agent/workspace/BuildTest_master
LocalGitDir=/home/jenkins/agent/workspace/BuildTest_master/.git
LocalGitStorageDir=/home/jenkins/agent/workspace/BuildTest_master/.git
LocalMediaDir=/home/jenkins/agent/workspace/BuildTest_master/.git/lfs/objects
LocalReferenceDirs=
TempDir=/home/jenkins/agent/workspace/BuildTest_master/.git/lfs/tmp
ConcurrentTransfers=8
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=/home/jenkins/agent/workspace/BuildTest_master/.git/lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic,lfs-standalone-file,ssh
UploadTransfers=basic,lfs-standalone-file,ssh
GIT_EXEC_PATH=/usr/lib/git-core
GIT_LFS_ENABLED=true
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

Config for good measure:
```
+ git config -l
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.process=git-lfs filter-process --skip
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge --skip -- %f
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
remote.origin.url=[https://x-token-auth:{**TOKEN**}@bitbucket.org/**USER**/**REPO**.git](https://x-token-auth:**TOKEN**@bitbucket.org/**USER**/**REPO**.git)
remote.origin.fetch=+refs/heads/master:refs/remotes/origin/master
lfs.repositoryformatversion=0
```

**Comment by frankvHoof93** [comment]
Update on this bug:
Using 'checkout scm' will cause it to fail.
Using the code below does actually get a proper pull from LFS (combined with the 'LFS pull after checkout'-step in the job configuration:

	sh 'git lfs install'
	script {
	def gitRemoteOriginUrl = scm.getUserRemoteConfigs()[0].getUrl()
	echo 'The remote URL is ' + gitRemoteOriginUrl
	
	// Running checkout scm fails with LFS, but this doesn't..
	
	scmVars = checkout([$class: 'GitSCM', 
		branches: [[name: 'refs/heads/$BRANCH_NAME']], 
		extensions: [
			[$class: 'GitLFSPull'],
			[$class: 'LocalBranch', localBranch: '**']
		], 
		userRemoteConfigs: [[credentialsId: 'Bitbucket_OAuth', url: gitRemoteOriginUrl]]])
	}

**Comment by sskjames** [comment]
I'm facing the same problem too. Hi @frankvHoof93, did you manage to solve this problem? Can you please share your findings?

**Comment by nfalco79** [comment]
I can not reproduce the issue
I have create a repository configuring LFS file of the repository
.gitattributes `files/* filter=lfs diff=lfs merge=lfs -text`
I setup a OAuth2 credentials
```
The recommended git tool is: NONE
using credential nfalco79.OAuth
 > git.exe rev-parse --resolve-git-dir D:\git\bitbucket-branch-source-plugin\work\workspace\nfalco79_test-lfs_master\.git # timeout=10
Fetching changes from the remote Git repository
 > git.exe config remote.origin.url https://bitbucket.org/nfalco79/test-lfs.git # timeout=10
Fetching without tags
Fetching upstream changes from https://bitbucket.org/nfalco79/test-lfs.git
 > git.exe --version # timeout=10
 > git --version # 'git version 2.47.1.windows.2'
using GIT_ASKPASS to set credentials 
 > git.exe fetch --no-tags --force --progress -- https://bitbucket.org/nfalco79/test-lfs.git +refs/heads/master:refs/remotes/origin/master # timeout=10
Checking out Revision 67ec3d25517bae734e0e2d40076931e01ab8073b (master)
Enabling Git LFS pull
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 67ec3d25517bae734e0e2d40076931e01ab8073b # timeout=10
 > git.exe config --get remote.origin.url # timeout=10
using GIT_ASKPASS to set credentials 
 > git.exe lfs pull origin # timeout=10
Commit message: "Add Jenkinsfile"
First time build. Skipping changelog.
[Bitbucket] Notifying commit build result
```

I do not know if the issue happens for private repository

**Comment by nfalco79** [comment]
If repository is private than checkout fail with a 403 (both OAuth2 and appPassowrd credentials):
```
using GIT_ASKPASS to set credentials OAuth2 token for nfalco79.OAuth
 > git.exe fetch --no-tags --force --progress -- https://bitbucket.org/nfalco79/test-lfs.git +refs/heads/master:refs/remotes/origin/master # timeout=10
ERROR: Error fetching remote repo 'origin'
hudson.plugins.git.GitException: Failed to fetch from https://bitbucket.org/nfalco79/test-lfs.git
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:999)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.retrieveChanges(GitSCM.java:1240)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM._checkout(GitSCM.java:1311)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.checkout(GitSCM.java:1278)
	at PluginClassLoader for workflow-scm-step//org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:136)
	at PluginClassLoader for workflow-scm-step//org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:101)
	at PluginClassLoader for workflow-scm-step//org.jenkinsci.plugins.workflow.steps.scm.SCMStep$StepExecutionImpl.run(SCMStep.java:88)
	at PluginClassLoader for workflow-step-api//org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:49)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: hudson.plugins.git.GitException: Command "git.exe fetch --no-tags --force --progress -- https://bitbucket.org/nfalco79/test-lfs.git +refs/heads/master:refs/remotes/origin/master" returned status code 128:
stdout: 
stderr: remote: The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.
fatal: unable to access 'https://bitbucket.org/nfalco79/test-lfs.git/': The requested URL returned error: 403

	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2852)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2188)
	at PluginClassLoader for git-client//org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:638)
	at PluginClassLoader for git//hudson.plugins.git.GitSCM.fetchFrom(GitSCM.java:997)
	... 12 more
ERROR: Error fetching remote repo 'origin'
ERROR: Maximum checkout retry attempts reached, aborting
```

Is this the error you refer in step 3 with "Checkout fails if LFS-files are present in the repository" ?

**Comment by nfalco79** [comment]
I had investigate a bit and search on google....than
Seems that bitbucket support only SSH and appPassword for user that enable "2AF" https://community.atlassian.com/forums/Bitbucket-questions/Bitbucket-LFS-Access-Keys-amp-2FA/qaq-p/787619. Other authentication method like HTTP Access Token are not.

[The author declare](https://github.com/git-lfs/git-lfs/issues/4060) that credentials can not be passed from Git to Git LFS. To share them it should rely on GCM (Git Credential Manager) using GIT_ASKPASS or SSH_ASKPASS than in our case are set [here](https://github.com/jenkinsci/git-client-plugin/blob/eff73111577a61b4c3a40dbc8bc4b5ede27e0cbc/src/main/java/org/jenkinsci/plugins/gitclient/CliGitAPIImpl.java#L2154). Or should be, because does not work, bitbucket return 403.

```
D:\git\bitbucket-branch-source-plugin\work\workspace\nfalco79_test-lfs_master>git lfs env 
git-lfs/3.6.1 (GitHub; windows amd64; go 1.23.3; git ea47a34b)
git version 2.47.1.windows.2

Endpoint=https://bitbucket.org/nfalco79/test-lfs.git/info/lfs (auth=none)
```
I thought the `(auth=none)` could be the issue for which it does not lookup from declared env variables.
I also try to force authentication as described [here](https://github.com/git-lfs/git-lfs/issues/2658#issuecomment-335508700) without luck.
The endpoint now seems to be configured to user basic auth (case of OAuth2, appPassoword or token case) but is always fail with 403
```
D:\git\bitbucket-branch-source-plugin\work\workspace\nfalco79_test-lfs_master>git config lfs.https://bitbucket.org/nfalco79/test-lfs.git.access basic 
[Pipeline] bat

D:\git\bitbucket-branch-source-plugin\work\workspace\nfalco79_test-lfs_master>git lfs env 
git-lfs/3.6.1 (GitHub; windows amd64; go 1.23.3; git ea47a34b)
git version 2.47.1.windows.2

Endpoint=https://bitbucket.org/nfalco79/test-lfs.git/info/lfs (auth=basic)
LocalWorkingDir=D:\git\bitbucket-branch-source-plugin\work\workspace\nfalco79_test-lfs_master
...
 > git.exe fetch --no-tags --force --progress -- https://bitbucket.org/nfalco79/test-lfs.git +refs/heads/master:refs/remotes/origin/master # timeout=10
ERROR: Error fetching remote repo 'origin'
...
Caused by: hudson.plugins.git.GitException: Command "git.exe fetch --no-tags --force --progress -- https://bitbucket.org/nfalco79/test-lfs.git +refs/heads/master:refs/remotes/origin/master" returned status code 128:
stdout: 
stderr: remote: The requested repository either does not exist or you do not have access. If you believe this repository exists and you have access, make sure you're authenticated.
fatal: unable to access 'https://bitbucket.org/nfalco79/test-lfs.git/': The requested URL returned error: 403
```

The only working use case is enforce the URL embedding credentials:
```
using GIT_ASKPASS to set credentials OAuth2 token for nfalco79.OAuth
...
 > git.exe fetch --no-tags --force --progress -- https://x-token-auth:****token***@bitbucket.org/nfalco79/test-lfs.git +refs/heads/master:refs/remotes/origin/master # timeout=10
Checking out Revision 354e527405b62459e0da9dd86eccf3cd718bb598 (master)
Enabling Git LFS pull
 > git.exe config core.sparsecheckout # timeout=10
 > git.exe checkout -f 354e527405b62459e0da9dd86eccf3cd718bb598 # timeout=10
 > git.exe config --get remote.origin.url # timeout=10
using GIT_ASKPASS to set credentials OAuth2 token for nfalco79.OAuth
 > git.exe lfs pull origin # timeout=10
Commit message: "Add Jenkinsfile"
 > git.exe rev-list --no-walk 5b865e0b817b1b73257a7cd0effed5eaf1dd889c # timeout=10
[Bitbucket] Notifying commit build result
```
But this option is not viable because it is a security risk (a SECURITY-3363 was already provide against this).
If someone have a working alternative to fix this issue are welcome.

@frankvHoof93 please fill and issue to JIRA issue tracker, I will report my considerations.
