### ISSUE TITLE
Fail to access Bitbucket

### ISSUE THREAD

**Issue by thematrixdev** [jenkinsci/bitbucket-branch-source-plugin#792]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.426.2
OS: Linux - 5.15.0-1051-aws
Java: 17.0.9 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
apache-httpcomponents-client-4-api:4.5.14-208.v438351942757
authentication-tokens:1.53.v1c90fd9191a_b_
bouncycastle-api:2.30.1.77-225.v26ea_c9455fd9
branch-api:2.1135.v8de8e7899051
caffeine-api:3.1.8-133.v17b_1ff2e0599
cloudbees-bitbucket-branch-source:856.v04c46c86f911
cloudbees-folder:6.858.v898218f3609d
credentials:1311.vcf0a_900b_37c2
credentials-binding:642.v737c34dea_6c2
display-url-api:2.200.vb_9327d658781
durable-task:523.va_a_22cf15d5e0
git:5.2.1
git-client:4.6.0
gson-api:2.10.1-3.vb_25b_599b_e4f8
handy-uri-templates-2-api:2.1.8-30.v7e777411b_148
instance-identity:185.v303dc7c645f9
ionicons-api:56.v1b_1c8c49374e
jackson2-api:2.15.3-372.v309620682326
jakarta-activation-api:2.0.1-3
jakarta-mail-api:2.0.1-3
javax-activation-api:1.2.0-6
javax-mail-api:1.6.2-9
jaxb:2.3.9-1
joda-time-api:2.12.5-5.v5495a_235fedf
mailer:463.vedf8358e006b_
mina-sshd-api-common:2.11.0-86.v836f585d47fa_
mina-sshd-api-core:2.11.0-86.v836f585d47fa_
pipeline-build-step:540.vb_e8849e1a_b_d8
pipeline-groovy-lib:689.veec561a_dee13
pipeline-input-step:477.v339683a_8d55e
pipeline-milestone-step:111.v449306f708b_7
pipeline-model-api:2.2151.ve32c9d209a_3f
pipeline-model-definition:2.2151.ve32c9d209a_3f
pipeline-model-extensions:2.2151.ve32c9d209a_3f
pipeline-stage-step:305.ve96d0205c1c6
pipeline-stage-tags-metadata:2.2151.ve32c9d209a_3f
plain-credentials:143.v1b_df8b_d3b_e48
scm-api:683.vb_16722fb_b_80b_
script-security:1294.v99333c047434
snakeyaml-api:2.2-111.vc6598e30cc65
ssh-credentials:308.ve4497b_ccd8f4
structs:325.vcb_307d2a_2782
trilead-api:2.133.vfb_8a_7b_9c5dd1
variant:60.v7290fc0eb_b_cd
workflow-aggregator:596.v8c21c963d92d
workflow-api:1283.v99c10937efcb_
workflow-basic-steps:1042.ve7b_140c4a_e0c
workflow-cps:3826.v3b_5707fe44da_
workflow-durable-task-step:1313.vcb_970b_d2a_fb_3
workflow-job:1385.vb_58b_86ea_fff1
workflow-multibranch:756.v891d88f2cd46
workflow-scm-step:415.v434365564324
workflow-step-api:639.v6eca_cd8c04a_a_
workflow-support:865.v43e78cc44e0d

  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 20.04

### Reproduction steps

- Freshly installed Jenkins LTS (container version)
- Only installed Pipeline plugin
- Installed Bitbucket Branch source plugin
- Created an App-Password on Bitbucket.org
- Added as username (not email) / password on Jenkins
- Created a multi-branch pipeline on Jenkins
- Chose the crediential, entered "project key" as "owner" on Jenkins

### Expected Results

List out repository names? (I have never seen the successful result)

### Actual Results

```
Started by user [dummyuser](https://jenkins.mydomain.com/user/dummyuser)
[Wed Dec 20 10:06:50 HKT 2023] Starting branch indexing...
ERROR: [Wed Dec 20 10:06:50 HKT 2023] Could not update folder level actions from source 20969e95-fc09-4388-9de7-35bb51e04d2f
[Wed Dec 20 10:06:50 HKT 2023] Finished branch indexing. Indexing took 0.72 sec
FATAL: Failed to recompute children of DummyProject
java.io.FileNotFoundException: URL: https://api.bitbucket.org/2.0/repositories/DUMMYPROJECTKEY/
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequestAsInputStream(BitbucketCloudApiClient.java:947)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRequest(BitbucketCloudApiClient.java:967)
	at com.cloudbees.jenkins.plugins.bitbucket.client.BitbucketCloudApiClient.getRepository(BitbucketCloudApiClient.java:391)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveActions(BitbucketSCMSource.java:1107)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:847)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:611)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:269)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:167)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1057)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE
```

### Anything else?

Tried using OAuth;
Tried without specifying "owner";
All did not work

**Comment by thematrixdev** [comment]
I have just found "owner" should be "workspace" on Bitbucket.org but not "project".

![image](https://github.com/jenkinsci/bitbucket-branch-source-plugin/assets/19472561/41929240-d53b-4e80-b4a9-12bac17c3a95)
