### ISSUE TITLE
Branches auto-discovering not working on Bitbucket server

### ISSUE THREAD

**Issue by maannima** [jenkinsci/bitbucket-branch-source-plugin#799]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Bitbucket Server v8.9.6
Jenkins 2.426.2
OS: Linux - 4.18.0-372.80.1.el8_6.x86_64
Java: 17.0.9 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
Bitbucket Branch Source Plugin 856.v04c46c86f911
Pipeline: Multibranch 756.v891d88f2cd46
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Bitbucket Server v8.9.6
Jenkins 2.426.2
OS: Linux - 4.18.0-372.80.1.el8_6.x86_64
Java: 17.0.9 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
Bitbucket Branch Source Plugin 856.v04c46c86f911
Pipeline: Multibranch 756.v891d88f2cd46

### Get credentials to access the Bitbucket API

Create a Bitbucket HTTP access tokens (project admin)

![image](https://github.com/jenkinsci/bitbucket-branch-source-plugin/assets/96467481/f2f29229-b8a4-479c-a50c-1035c914792f)

### Bitbucket Endpoints configuration in Jenkins > Manage Jenkins
Added Jenkins Credentials:
- Scope: Global Credentials
- Copy paste the HTTP access token, starting with BBDC-
- Kind: Username with password
- Username: Bitbucket project key (INFSCR)
- Id blank (so auto-generated)
- Description: Name of Http access key

![image](https://github.com/jenkinsci/bitbucket-branch-source-plugin/assets/96467481/f720adb7-3714-4d8c-a6fd-ece6f01d03c4)

### Configure the multi-branch project source
- Selected the correct Bitbucket URL
- Used the Bitbucket project key for Owner

![image](https://github.com/jenkinsci/bitbucket-branch-source-plugin/assets/96467481/f8e7d5d6-f1f6-46c2-9c10-07b756e42015)

### Expected Results

Expected was a working integration between Jenkins and Bitbucket server. But the Repository Name in Branch Sources can't be filled in and doesn't show a drop down.

### Actual Results

Repository Name in Branch Sources can't be filled in and doesn't show a drop down.
![image](https://github.com/jenkinsci/bitbucket-branch-source-plugin/assets/96467481/83128ffa-9aa5-4173-b5df-ce19471c879d)

### Anything else?

As a result the Scan Multibranch Pipeline Logs show the following

`[Wed Jan 17 13:54:57 UTC 2024] Starting branch indexing...
ERROR: [Wed Jan 17 13:54:57 UTC 2024] Could not update folder level actions from source f0326964-f8d1-41b6-9041-46ce232fcc15
[Wed Jan 17 13:54:57 UTC 2024] Finished branch indexing. Indexing took 9 ms
FATAL: Failed to recompute children of tests » stack-aws-container-registery-maianni1-test
com.cloudbees.jenkins.plugins.bitbucket.api.BitbucketRequestException: HTTP request error. Status: 403: .
HttpResponseProxy{HTTP/1.1 403  [Date: Wed, 17 Jan 2024 13:54:57 GMT, Content-Type: application/json;charset=UTF-8, Content-Length: 70, Connection: keep-alive, Set-Cookie: AWSALB=z+cAOlLFOnOuMM++etnNvbLkfogJt4wOp3Tm97i//z27yGJr+O+qiXCSfSXCM5R1TLM7H+Yq+PnGj0+UTeZsn4ovzEcfYktOOMRSbJFalpsFKoQsQ5hFBCturSlE; Expires=Wed, 24 Jan 2024 13:54:57 GMT; Path=/, Set-Cookie: AWSALBCORS=z+cAOlLFOnOuMM++etnNvbLkfogJt4wOp3Tm97i//z27yGJr+O+qiXCSfSXCM5R1TLM7H+Yq+PnGj0+UTeZsn4ovzEcfYktOOMRSbJFalpsFKoQsQ5hFBCturSlE; Expires=Wed, 24 Jan 2024 13:54:57 GMT; Path=/; SameSite=None; Secure, X-AREQUESTID: *VA1LQ8x834x14525318x1] ResponseEntityProxy{[Content-Type: application/json;charset=UTF-8,Content-Length: 70,Chunked: false]}}
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRequest(BitbucketServerAPIClient.java:978)
	at com.cloudbees.jenkins.plugins.bitbucket.server.client.BitbucketServerAPIClient.getRepository(BitbucketServerAPIClient.java:494)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveActions(BitbucketSCMSource.java:1107)
	at jenkins.scm.api.SCMSource.fetchActions(SCMSource.java:847)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:611)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:269)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:167)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1057)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE`

**Comment by andygoossens** [comment]
You claim to be using Bitbucket Server, but I assume that is a mistake on your part. Only Bitbucket Data Center has support for HTTP access tokens:
https://confluence.atlassian.com/bitbucketserver089/http-access-tokens-1236435579.html#HTTPaccesstokens-CreateHTTPaccesstokensforprojectsorrepositories

**Comment by maannima** [comment]
The differentiation I'm aware of is between Bitbucket Server and Bitbucket Cloud. Bitbucket Server is a self-hosted solution, often deployed in a Data Center. This is the method I am using.

**Comment by Enrice** [comment]
I don't think you can use the project key as the credentials user name. Try with a real user or, as may have been your intention, follow:
[](https://confluence.atlassian.com/bitbucketserver0819/http-access-tokens-1416825778.html?utm_campaign=in-app-help&utm_medium=in-app-help&locale=de_DE%2Cde&utm_source=stash#HTTPaccesstokens-UsingHTTPaccesstokens)
This way you may redefine your credentials not be username/password to reflect the bearer authentication.

**Comment by nfalco79** [comment]
Thanks @Enrice (thanks). Reading the documentation I see
> For project or repository tokens, you must only use Bearer Auth without the username:
> 
> curl -H 'Authorization: Bearer MDM0MjM5NDc2MDxxxxxxxxxxxxxxxxxxxxx'

**Comment by nfalco79** [comment]
I'm closing this issue because the repository/project HTTP access token is not supported by this plugin as per documentation. Only personal access token is supported for Bitbucket Server/Datacenter.

This issue duplicates feature request #716
