### ISSUE TITLE
java.lang.IllegalStateException: Can't find clone link for protocol HTTP

### ISSUE THREAD

**Issue by cbolson1** [jenkinsci/bitbucket-branch-source-plugin#866]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
bitbucket branch source plugin version = 888.v8e6d479a_1730
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Oracle Linux

### Reproduction steps

1. install plugin version 871.v28d74e8b_4226
2. Configure plugin to use Personal Access Token to read list of projects in Bitbucket
3. Configure plugin to use Access Key to read specific Bitbucket repository
4. Configure the plugin to use "checkout over SSH"

### Expected Results

Check out the code from the specified repo

### Actual Results

```
Looking up Wainwright/sidecar for branches
Checking branch master from Wainwright/sidecar
      ‘jenkins/sidecar.groovy’ found
    Met criteria
ERROR: [Mon Jul 29 15:05:11 GMT 2024] Could not fetch branches from source 354743ac-03b3-4fe9-aeca-236e377ad636
[Mon Jul 29 15:05:11 GMT 2024] Finished branch indexing. Indexing took 4.5 sec
FATAL: Failed to recompute children of Sidecar
java.lang.IllegalStateException: Can't find clone link for protocol HTTP
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.lambda$getCloneLink$1(BitbucketGitSCMBuilder.java:313)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.getCloneLink(BitbucketGitSCMBuilder.java:313)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withPrimaryRemote(BitbucketGitSCMBuilder.java:300)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withBranchRemote(BitbucketGitSCMBuilder.java:293)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withBitbucketRemote(BitbucketGitSCMBuilder.java:199)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withCloneLinks(BitbucketGitSCMBuilder.java:130)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.build(BitbucketSCMSource.java:1034)
	at jenkins.scm.api.SCMSource.build(SCMSource.java:934)
	at jenkins.branch.MultiBranchProject.newBranch(MultiBranchProject.java:556)
	at jenkins.branch.MultiBranchProject$SCMHeadObserverImpl.observe(MultiBranchProject.java:2009)
	at jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:357)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveBranches(BitbucketSCMSource.java:793)
	at com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:633)
	at jenkins.scm.api.SCMSource._retrieve(SCMSource.java:372)
	at jenkins.scm.api.SCMSource.fetch(SCMSource.java:282)
	at jenkins.branch.MultiBranchProject.computeChildren(MultiBranchProject.java:654)
	at com.cloudbees.hudson.plugins.folder.computed.ComputedFolder.updateChildren(ComputedFolder.java:269)
	at com.cloudbees.hudson.plugins.folder.computed.FolderComputation.run(FolderComputation.java:167)
	at jenkins.branch.MultiBranchProject$BranchIndexing.run(MultiBranchProject.java:1057)
	at hudson.model.ResourceController.execute(ResourceController.java:101)
	at hudson.model.Executor.run(Executor.java:442)
Finished: FAILURE
```

### Anything else?

This appears to be directly related to #804 .  However, I tried the latest plugin version (888.v8e6d479a_1730), and that still shows this problem.  Therefore I'm tempted to believe that #804 is not solved.

### Are you interested in contributing a fix?

No

**Comment by rpaasche** [comment]
Had the same issue, could be fixed by run "Scan Organization Folder" manualy. The most recent version [888.v8e6d479a_1730](https://updates.jenkins.io/download/plugins/cloudbees-bitbucket-branch-source/888.v8e6d479a_1730/cloudbees-bitbucket-branch-source.hpi)
 is working just fine.

**Comment by cbolson1** [comment]
One potentially important distinction here, I'm using the "checkout over SSH" feature in my job configuration.

**Comment by rpaasche** [comment]
> I just have a single multibranch pipeline job setup; I don't have an organization folder configured here. Therefore, I don't think I can do what you are suggesting.

In this case, it would be "Scan Multibranch Pipeline". Navigate to your job and it should be on the left side.

> One potentially important distinction here, I'm using the "checkout over SSH" feature in my job configuration.

I do the same.

**Comment by cbolson1** [comment]
> Navigate to your job and it should be on the left side.

Yep. I did that.  I still get the error message I posted in this issue.

**Comment by davehewitt** [comment]
Hi, I am experiencing this issue with the latest version of the plugin, 888.v8e6d479a_1730 .  I have been forced to keep this plugin downgraded due to this issue.

**Comment by nfalco79** [comment]
Do you have a Bitbucket server instance installed in the local NET? I do not know how DataCenter or Cloud instances can expose HTTP protocol instead of HTTPS.
We are using cloud so other instance kinds I do not know how configurations/features differ by the cloud type.

**Comment by cbolson1** [comment]
@nfalco79 was 5b9b36e0379ee01d394d5745140cf7a81b1154ea an attempt to fix this issue?

**Comment by nfalco79** [comment]
No it was done to fix a regression where clone links (regardless the protocol) was not set anymore in commit https://github.com/jenkinsci/bitbucket-branch-source-plugin/commit/6e501b97d2dc8067444729393faf58b142b574a3

Regression was introduced after 888.v8e6d479a_1730 so I think does not resolve this issue, maybe could. If you have a chance to test latest version a report a feedback it would be great.

**Comment by SunMar** [comment]
Also ran into this issue today, was using the latest release, reverting to `866.vdea_7dcd3008e` solved the issue.

@nfalco79 If you have some steps for me on how I can build the plugin from source I don't mind doing a little bit of debugging and see if I can find the issue. I'm not a Java developer however, so I'm not familiar with the ecosystem and things like Maven, so would need a step by step what commands to run to end up with a package that I can directly upload in my Jenkins. But I have a test Jenkins running on my machine where I could quickly iterate with debugging.

**Comment by SunMar** [comment]
@nfalco79 Managed to figure out how to build the package and did some debugging. The regression comes from commit ad359b3.

Here `credentialsId` is now passed as `null`:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/89ddddb45079b788a38147fbd48460a202d9ad8e/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketSCMSource.java#L1007

This affects the `withCredentials()` call in `BitbucketGitSCMBuilder`:
https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/89ddddb45079b788a38147fbd48460a202d9ad8e/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/BitbucketGitSCMBuilder.java#L159-L180

If `credentialsId` is set, it checks `scmSource.getCheckoutCredentialsId()` and if that is set, it switches to those credentials including the applicable protocol. If you are using `SSHCheckoutTrait` then `getCheckoutCredentialsId()` will return the SSH credentials id set in the trait and overrides the HTTP access token credentials.
Because `credentialsId` is now `null`, it never checks for the SSH credentials and defaults to using HTTP, which fails because our Bitbucket server does not allow HTTP checkouts.

Hopefully this helps.

**Comment by nfalco79** [comment]
Thanks to dig into the issue, unfortunately this will be resolved by PR #867 but it is blocked by https://github.com/jenkinsci/git-plugin/pull/1649

**Comment by SunMar** [comment]
@nfalco79 thanks! I notice though that https://github.com/jenkinsci/git-plugin/pull/1649 is already merged, did you maybe mean https://github.com/jenkinsci/git-plugin/pull/1687 ? I see that PR is referenced there and still open.

**Comment by cbolson1** [comment]
I just tried this again today with the latest release, and I'm still running into the same issue

Here's a copy of my log after I click on *Scan Multibranch Pipeline Now*.  This was the log from `933.0.2`:

```
Started by user Corey
[Mon Dec 16 17:37:21 GMT 2024] Starting branch indexing...
Connecting to https://bitbucket.<company>/ using Read Access Token for Jenkins to Read Wainwright Project in Bitbucket
Looking up Wainwright/sidecar for branches
Checking branch master from Wainwright/sidecar
      ‘jenkins/sidecar.groovy’ found
    Met criteria
ERROR: [Mon Dec 16 17:37:30 GMT 2024] Could not fetch branches from source 354743ac-03b3-4fe9-aeca-236e377ad636
[Mon Dec 16 17:37:30 GMT 2024] Finished branch indexing. Indexing took 8.9 sec
FATAL: Failed to recompute children of Sidecar
java.lang.IllegalStateException: Can't find clone link for protocol HTTP
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.lambda$getCloneLink$1(BitbucketGitSCMBuilder.java:320)
	at java.base/java.util.Optional.orElseThrow(Optional.java:403)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.getCloneLink(BitbucketGitSCMBuilder.java:320)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withPrimaryRemote(BitbucketGitSCMBuilder.java:307)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withBranchRemote(BitbucketGitSCMBuilder.java:300)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withBitbucketRemote(BitbucketGitSCMBuilder.java:206)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketGitSCMBuilder.withCloneLinks(BitbucketGitSCMBuilder.java:138)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.build(BitbucketSCMSource.java:1032)
	at PluginClassLoader for scm-api//jenkins.scm.api.SCMSource.build(SCMSource.java:934)
	at PluginClassLoader for branch-api//jenkins.branch.MultiBranchProject.newBranch(MultiBranchProject.java:564)
	at PluginClassLoader for branch-api//jenkins.branch.MultiBranchProject$SCMHeadObserverImpl.observe(MultiBranchProject.java:2017)
	at PluginClassLoader for scm-api//jenkins.scm.api.trait.SCMSourceRequest.process(SCMSourceRequest.java:357)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieveBranches(BitbucketSCMSource.java:793)
	at PluginClassLoader for cloudbees-bitbucket-branch-source//com.cloudbees.jenkins.plugins.bitbucket.BitbucketSCMSource.retrieve(BitbucketSCMSource.java:633)
	at PluginClassLoader for scm-api//jenkins.scm.api.SCMSource._retrieve(SCMSource.java:372)
	at PluginClassLoader for scm-api//jenkins.scm.api.SCMSource.fetch(SCMSource.java:282)
```

**Comment by SunMar** [comment]
@cbolson1 if I'm not mistaken this fix is pending a release of the Git plugin. Installing the latest master version of the Bitbucket Branch Source and Git plugins solves the issue for me.

You can find the master branch builds as artifacts here (grab the `.hpi` file):
https://ci.jenkins.io/job/Plugins/job/git-plugin/job/master/
https://ci.jenkins.io/job/Plugins/job/bitbucket-branch-source-plugin/job/master/
